POST http://localhost:9080/register HTTP/1.1
Content-Type: application/json
{
  "username": "Deval912",
  "password": "a",
  "email": "deval@gmail.com",
  "name": "deval"
}

POST http://localhost:9080/login HTTP/1.1
Content-Type: application/json

{
  "email": "deval@gmail.com",
  "password": "a"
}

POST http://localhost:9080/login HTTP/1.1
Content-Type: application/json

{
  "email": "deval@gmail.com",
  "password": "a"
}

GET http://localhost:9080/get_user_and_profile
Content-Type: application/json

{
  "token": "1b389be710b8637e72fbf246f558799bf2853808314a76b2f350a6eea61581b"
}

POST http://localhost:9080/update_profile_picture
Content-Type: application/json

{
  "token": "1b389be710b8637e72fbf246f558799bf2853808314a76b2f350a6eea61581b",
  "bio"
  "currentPost": "CTO",
  "Pastwork": [
    {
      "company" : "Microsoft",
      "position" : "CTO",
      "years" : "2+"
    }
  ],
  "education" : [
    {
      "school" : "IIT",
      "degree" : "B.Tech",
      "field-of-study" : "2015-2019"
    }
  ]
}

GET http://localhost:9080/get_all_users